services:
  game-server:
    build: .
    platform: linux/amd64
    ports:
      - "7777:7777/udp"
    restart: unless-stopped
    environment:
      - GODOT_SERVER=true
    volumes:
      - ./server_data:/app/data
